### ISSUE TITLE
Syntax error on WP Rocket's compatibility file: __ return_empty_array()

### ISSUE THREAD

**Issue by alfonso100** [Servebolt/servebolt-optimizer#426]
Hey folks!
Alfonso here, from the WP Rocket support team. 

A mutual customer is having a fatal error after enabling **WP Rocket** and **Serverbolt Optimizer** at the same time. 

It is happening here: https://github.com/Servebolt/servebolt-optimizer/blob/master/src/Servebolt/Compatibility/WpRocket/DisableWpRocketCache.php#L25

It seems on line 25 there is an unexpected space at `__ return_empty_array()`
Screenshot: https://i.imgur.com/k41D7eO.png

the error is: 
```
[14-Dec-2022 20:26:27 UTC] PHP Fatal error:  Uncaught TypeError: call_user_func_array(): Argument #1 ($callback) must be a valid callback, function "__ return_empty_array" not found or invalid function name in /path/public/wp-includes/class-wp-hook.php:308
Stack trace:
#0 /path/public/wp-includes/plugin.php(205): WP_Hook->apply_filters()
#1 /path/public/wp-content/plugins/wp-rocket1/inc/functions/options.php(307): apply_filters()
#2 /path/public/wp-content/plugins/wp-rocket1/inc/functions/files.php(154): get_rocket_cache_mandatory_cookies()
#3 /path/public/wp-content/plugins/wp-rocket1/inc/functions/files.php(212): get_rocket_config_file()
#4 /path/public/wp-content/plugins/wp-rocket1/inc/admin/admin.php(267): rocket_generate_config_file()
#5 /path/public/wp-includes/class-wp-hook.php(308): rocket_maybe_generate_config_files()
#6 /path/public/wp-includes/class-wp-hook.php(332): WP_Hook->apply_filters()
#7 /path/public/wp-includes/plugin.php(517): WP_Hook->do_action()
#8 /path/public/wp-admin/admin.php(175): do_action()
#9 /path/public/wp-admin/plugins.php(10): require_once('...')
#10 {main}
  thrown in /path/public/wp-includes/class-wp-hook.php on line 308
```

thanks!

**Comment by andykillen** [comment]
Hey Alfonso, 

Thanks for your input, I've made the change and will release it in the next version 3.5.11 shortly. 

https://github.com/Servebolt/servebolt-optimizer/commit/d6d11765365646225ae98fbbcf9e2a5a0e2fa6e2

Feel free to make PR's in future :)
